In [ ]:
import pathlib
import sys

import pandas as pd
import umap
from notebook_init_utils import bandicoot_check, init_notebook

root_dir, in_notebook = init_notebook()

profile_base_dir = bandicoot_check(
    pathlib.Path("/home/lippincm/mnt/bandicoot").resolve(), root_dir
)

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
patient_ids = pd.read_csv(
    pathlib.Path(f"{root_dir}/data/patient_IDs.txt").resolve(strict=True),
    header=None,
    sep="\t",
    names=["patient_id"],
)["patient_id"].to_list()

viabilities_path = pathlib.Path(f"{root_dir}/data/viabilities/").resolve(strict=True)

In [ ]:
patient = "NF0014_T1"

In [ ]:
sc_agg_df = pd.read_parquet(
    pathlib.Path(
        f"{root_dir}/data/profiles_3D/{patient}/7.aggregated_profiles/sc_agg_well_level.parquet"
    ).resolve(strict=True)
)
sc_agg_df.head()

,Metadata_Biology_PatientTumor,Metadata_Experiment_Well,Cell_AGP_Granularity_1,Cell_AGP_Intensity_MaxIntensity,Cell_DNA-AGP_Colocalization_Correlation,Cell_DNA-AGP_Colocalization_MandersCoeffCostesM1,Cell_DNA-AGP_Colocalization_OverlapCoeff,Cell_DNA-AGP_Colocalization_RankWeightedColocalizationCoeff1,Cell_DNA-ER_Colocalization_Correlation,Cell_DNA-ER_Colocalization_MandersCoeffCostesM1,...,Nuclei_Mito-AGP_Colocalization_RankWeightedColocalizationCoeff1,Nuclei_Mito_Granularity_1,Nuclei_Mito_Intensity_IntegratedIntensity,Nuclei_Mito_Intensity_MassDisplacement,Nuclei_Mito_Intensity_MaxIntensity,Nuclei_Mito_Intensity_StdIntensity,Nuclei_Mito_Intensity_StdIntensityEdge,Nuclei_NoChannel_AreaSizeShape_BboxVolume,Nuclei_NoChannel_AreaSizeShape_Extent,Nuclei_NoChannel_AreaSizeShape_Volume
0,NF0014_T1,C10,-0.540915,1.812694,0.099624,0.358622,-1.184301,0.674418,-0.202966,-0.025300,...,0.095621,0.406931,-0.680764,0.906930,0.963558,3.246383,2.718007,-1.049103,-0.531284,-0.984486
1,NF0014_T1,C11,1.243436,-1.601916,-0.724108,-0.955643,-1.434578,-0.981273,-0.235177,-0.163773,...,0.374842,-0.889445,-1.310905,0.547117,0.289067,1.251520,1.292021,-2.640836,-0.811344,-2.652221
2,NF0014_T1,C2,26.470716,-0.632335,-0.814746,-0.912427,-1.415185,-0.633550,-1.375541,-1.108156,...,2.462408,4.377544,-0.292101,15.459417,4.721435,23.120541,24.480848,-1.286814,-0.075797,-1.770976
3,NF0014_T1,C3,0.744347,-1.981317,-0.699606,-1.079659,-1.410073,-0.896713,-0.947331,-0.639406,...,0.972839,0.794515,-1.280559,0.682771,-1.059914,-0.193342,-0.231857,-0.812243,-0.069976,-1.814013
4,NF0014_T1,C4,0.218976,0.590179,-0.258864,-0.087859,-0.497949,-0.456913,-0.735630,-0.623752,...,-0.537200,0.445816,-0.283181,-0.368225,-0.578135,-0.513760,-0.497514,-0.136593,0.370543,-0.040487

In [ ]:
viabilities_df = pd.read_csv(viabilities_path / f"{patient}_Viabilities.csv")
viabilities_df

             Drug  Concentration_uM  Viability_percentage
0       Onalespib                 1             32.645151
1         Digoxin                 1             22.499116
2      Trametinib                 1             69.366956
3    Fimepinostat                 1             39.494294
4       Rapamycin                 1             70.418039
5      Trametinib                10             69.850317
6     Selumetinib                 1             83.461964
7      Copanlisib                 1             45.043833
8       Nilotinib                 1            103.699313
9     Binimetinib                 1             95.746646
10     Linsitinib                 1             79.531230
11     Everolimus                 1             79.889192
12      PD0325901                10             70.700760
13    Binimetinib                10             87.146456
14    Selumetinib                10             90.552788
15      PD0325901                 1             93.769879
16      Ketotifen                 1            112.776023
17       Imatinib                 1            114.157708
18   Cabozantinib                 1            118.802084
19  Staurosporine                10              5.515339
20           DMSO                 0            100.000000